version: 2.1
aliases:
  - &run_yarn
    run:
      name: Install Packages
      command: yarn --frozen-lockfile
orbs:
  node: circleci/node@latest
jobs:
  setup:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: NodeJs Version
          command: node --version
      - *run_yarn
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - *run_yarn
      - run:
          name: Linter
          command: yarn lint
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - *run_yarn
      - run:
          name: Run Unity Tests
          command: yarn test

workflows:
  stable:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup