version: 2.1
aliases:
  - &run_yarn
    run:
      name: Install Packages
      command: yarn --frozen-lockfile

jobs:
  setup:
    - checkout
    - run:
        name: NodeJs Version
        command: node --version
    - *run_yarn
  lint:
    steps:
      - checkout
      - *run_yarn
      - run:
          name: Linter
          command: yarn lint
  test:
    steps:
      - checkout
      - *run_yarn
      - run:
          name: Run Unity Tests
          command: yarn test

workflows:
  stable:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup